#!/bin/bash -e

set -o pipefail
set -x

DB_NAME=otrs
BIN=/usr/share/otrs/bin

service mysql start

set +x
ADMIN_PASS=turnkey
mysqladmin --user=root --password="$MYSQL_PASS" create "$DB_NAME" \
    --default-character-set=utf8

cat <<EOF | debconf-set-selections
otrs2   otrs2/app-password-confirm  password turnkey
otrs2   otrs2/password-confirm  password turnkey
otrs2   otrs2/mysql/admin-pass  password
otrs2   otrs2/mysql/admin-user  string  root
otrs2   otrs2/dbconfig-install  boolean true
otrs2   otrs2/internal/reconfiguring    boolean false
otrs2   otrs2/install-error select  abort
otrs2   otrs2/database-type select  mysql
otrs2   otrs2/mysql/method  select  Unix socket
otrs2   otrs2/internal/skip-preseed boolean false
otrs2   otrs2/db/dbname string  $DB_NAME
otrs2   otrs2/upgrade-backup    boolean true
otrs2   otrs2/upgrade-error select  abort
otrs2   otrs2/dbconfig-reinstall    boolean false
otrs2   otrs2/db/app-user   string  $DB_NAME@localhost
otrs2   otrs2/dbconfig-remove   boolean true
otrs2   otrs2/passwords-do-not-match    error   
otrs2   otrs2/missing-db-package-error  select  abort
otrs2   otrs2/remote/port   string  
otrs2   otrs2/remote/host   select  localhost
otrs2   otrs2/purge boolean false
otrs2   otrs2/dbconfig-upgrade  boolean true
otrs2   otrs2/remote/newhost    string  
otrs2   otrs2/remove-error  select  abort
EOF

apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes otrs2

/usr/sbin/runuser -u otrs -- env LC_ALL=C.UTF-8 \
    "$BIN/otrs.Console.pl" Admin::User::SetPassword root@localhost "$ADMIN_PASS"
unset ADMIN_PASS MYSQL_PASS
set -x

otrs_version=$(dpkg-query -W -f='${Version}' otrs2)
install -d -m 0755 /usr/local/share/turnkey-otrs
cat > /usr/local/share/turnkey-otrs/source <<EOF
package=otrs2
installed_version=$otrs_version
repository=Debian 13 Trixie non-free
channel=Debian stable packages for Znuny 6.5 LTS
EOF

$BIN/otrs.SetPermissions.pl \
    --otrs-user=otrs --web-group=www-data --admin-group=root

ln -sf /usr/lib/ispell/american.hash /usr/lib/ispell/english.hash

service apache2 start
echo '# TurnKey uses /etc/otrs/apache.conf via the otrs2 site.' \
    > /etc/apache2/conf-enabled/otrs2.conf
ln -s /etc/otrs/apache.conf /etc/apache2/sites-available/otrs2.conf
rm -r /var/www/html/
a2dissite 000-default
a2ensite otrs2
a2enmod cgid

sed -i 's/^#MAILTO=\(.*\)$/MAILTO=\1/' /etc/otrs/cron

install -d -o otrs -g www-data -m 0770 /run/otrs
[ -L /etc/cron.d/otrs2 ]
grep -q 'otrs.Daemon.pl start' /etc/cron.d/otrs2

service mysql stop
service apache2 stop
