#!/bin/bash -e
# regenerate otrs mysql password

. /etc/default/inithooks

PASSWORD=$(mcookie)

CONF=/etc/dbconfig-common/otrs2.conf
sed -i "s/dbc_dbpass=\(.*\)/dbc_dbpass=\'$PASSWORD\'/" "$CONF"
dbconfig-generate-include -f perl "$CONF" /etc/otrs/database.pm

"$INITHOOKS_PATH/bin/mysqlconf.py" --user=otrs --pass="$PASSWORD"
unset PASSWORD

systemctl restart apache2
